---
# Variables: 
# static_domain
# admin_email

- name: Install apache
  apt: name={{item}} state=present
  with_items:
    - apache2
  become: yes
  become_user: root

- name: Deploy apache configuration for static site
  template: src=static.conf.j2 dest=/etc/apache2/sites-available/static.conf mode=0644
  become: yes
  become_user: root

- name: Enable static configuration
  file: src=/etc/apache2/sites-available/static.conf dest=/etc/apache2/sites-enabled/static.conf state=link
  become: yes
  become_user: root

- name: Disable default configuration
  file: path=/etc/apache2/sites-enabled/000-default.conf follow=no state=absent
  become: yes
  become_user: root

- name: Install letsencrypt certificate
  include: ../../letsencrypt/tasks/main.yml secure_domain={{static_domain}}
  # note that the letsencrypt certbot restarts apache
