---
- name: Update package cache
  apt: update_cache=yes
  become: yes
  become_user: root

- name: Install base packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - python-pip
    - git
    - nano
    - mosh
  become: yes
  become_user: root

