---
# Variables:
# piwik_domain
# admin_email

- name: Install apache and PHP
  apt: name={{item}} state=present
  with_items:
    - apache2
    - php5-curl
    - php5-gd
    - php5-cli
    - php5-geoip
    - mariadb-server
    - mariadb-client
    - python-mysqldb
    - unzip
  become: yes
  become_user: root

# TODO:
# I am affected by [this bug](https://github.com/ansible/ansible/issues/11348)
# so the file must be extracted manually, not through ansible
# - name: Fetch piwik
#   unarchive:
#     src: http://builds.piwik.org/piwik.zip
#     dest: /var/www/
#     copy: no
#     # piwik.zip contains piwik/ which gets extracted to /var/www/piwik
#   become: yes
#   become_user: root

- name: Remove extra files
  file:
    name: "/var/www/How to install Piwik.html"
    state: absent
  become: yes
  become_user: root

- name: Change permissions
  file: name=/var/www/piwik/tmp mode=0777
  become: yes
  become_user: root

- name: Change permissions 2
  file: name=/var/www/piwik/config mode=0777
  become: yes
  become_user: root

# TODO: I am affected by the following bug
# https://forum.piwik.org/t/always-populate-raw-post-data-1-and-yes-id-did-it/16664/7

- name: Set up database
  include: ../../mysql/tasks/main.yml db_name=piwik

- name: Install configuration for piwik
  template: src=piwik.conf.j2 dest=/etc/apache2/sites-available/piwik.conf mode=0600
  become: yes
  become_user: root

- name: Enable piwik site
  file: src=/etc/apache2/sites-available/piwik.conf dest=/etc/apache2/sites-enabled/piwik.conf state=link
  become: yes
  become_user: root

- name: Install letsencrypt certificate
  include: ../../letsencrypt/tasks/main.yml secure_domain={{piwik_domain}}
  # note that the letsencrypt certbot restarts apache
