---
- name: Install owncloud and dependencies
  apt: name={{item}} state=present
  with_items:
    - owncloud
    - mariadb-server
    - mariadb-client
    - python-mysqldb
  become: yes
  become_user: root

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes
  become: yes
  become_user: root

- name: Change root password
  mysql_user:
      name: root 
      host: localhost
      password: "{{ db_root_password }}"

- name: Remember root password
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600

- name: Create Application Database
  mysql_db: name={{db_name}} state=present
  
- name: Create Application DB User
  mysql_user: name={{db_user}} password={{db_password}} priv={{db_name}}.*:ALL host=localhost state=present

- name: Deploy apache configuration for owncloud
  template: src=owncloud.conf.j2 dest=/etc/apache2/sites-available/owncloud.conf mode=0600
  become: yes
  become_user: root

- name: Disable defualt owncloud configuration
  file: path=/etc/apache2/conf-enabled/owncloud.conf follow=no state=absent
  become: yes
  become_user: root

- name: Enable ssl module
  apache2_module: name=ssl state=present
  become: yes
  become_user: root

- name: Enable custom owncloud site
  file: src=/etc/apache2/sites-available/owncloud.conf dest=/etc/apache2/sites-enabled/owncloud.conf state=link
  become: yes
  become_user: root

- name: Restart apache2
  service: name=apache2 state=restarted
  become: yes
  become_user: root

- name: Install letsencrypt
  git: repo=https://github.com/letsencrypt/letsencrypt dest=~/letsencrypt

- name: Get the username
  command: whoami
  register: username

- name: Get letsencrypt certificate
  command: /home/{{username.stdout}}/letsencrypt/certbot-auto certonly --apache --non-interactive --email {{email}} --domain {{owncloud_url}}
  args: chdir=/home/{{username.stdout}}/letsencrypt creates=/etc/letsencrypt/live/{{owncloud_url}}/cert.pem
  register: test1
  become: yes
  become_user: root

- name: Install letsencrypt certificate
  command: /home/{{username.stdout}}/letsencrypt/certbot-auto install --apache --non-interactive --domain {{owncloud_url}} --cert-path /etc/letsencrypt/live/{{owncloud_url}}/cert.pem --key-path /etc/letsencrypt/live/{{owncloud_url}}/privkey.pem --fullchain-path /etc/letsencrypt/live/{{owncloud_url}}/fullchain.pem --chain-path /etc/letsencrypt/live/{{owncloud_url}}/chain.pem --redirect --hsts --domain {{owncloud_url}}
  args: chdir=/home/{{username.stdout}}/letsencrypt
  register: test2
  become: yes
  become_user: root
