---
# based on https://www.rosehosting.com/blog/script-install-owncloud-on-an-ubuntu-12-04-vps/
# and https://doc.owncloud.org/server/9.0/admin_manual/installation/source_installation.html
- name: Install owncloud and dependencies
  apt: name={{item}} state=present
  with_items:
    - apache2
    - mariadb-server
    - libapache2-mod-php5
    - php5-gd
    - php5-json
    - php5-mysql
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-imagick
    - php5-ldap
  become: yes
  become_user: root

- name: Download and extract owncloud
  unarchive:
    # TODO: change the version number automatically
    src: https://download.owncloud.org/community/owncloud-9.0.2.tar.bz2
    copy: no
    dest: /var/www/
  become: yes
  become_user: root

# TODO: verify SHA256 and PGP signature

- name: Deploy apache configuration for owncloud
  template: src=owncloud.conf.j2 dest=/etc/apache2/sites-available/owncloud.conf mode=0600
  become: yes
  become_user: root

# TOOD: rename
- name: Enable apache configuration for owncloud
  file: src=/etc/apache2/sites-available/owncloud.conf dest=/etc/apache2/sites-enabled/owncloud.conf state=link
  become: yes
  become_user: root

- name: Enable rewrite
  apache2_module: state=present name=rewrite

- name: Enable rewrite
  apache2_module: state=present name=headers

- name: Enable rewrite
  apache2_module: state=present name=env

- name: Enable rewrite
  apache2_module: state=present name=dir

- name: Enable rewrite
  apache2_module: state=present name=mime

- name: Change permissions on owncloud
  # TODO: what user/group goes here
  file:
    group: www-data
    owner: www-data
    path: /var/www/owncloud
    state: directory
    recurse: yes
  become: yes
  become_user: root

- name: Setup database
  include: ../mysql/tasks/main.yml db_name=owncloud
  
- name: Restart apache2
  service: name=apache2 state=restarted
  become: yes
  become_user: root

# - name: Install letsencrypt
#   git: repo=https://github.com/letsencrypt/letsencrypt dest=~/letsencrypt

# - name: Get the username
#   command: whoami
#   register: username

# - name: Get letsencrypt certificate
#   command: /home/{{username.stdout}}/letsencrypt/certbot-auto certonly --apache --non-interactive --email {{email}} --domain {{owncloud_url}}
#   args: chdir=/home/{{username.stdout}}/letsencrypt creates=/etc/letsencrypt/live/{{owncloud_url}}/cert.pem
#   register: test1
#   become: yes
#   become_user: root

# - name: Install letsencrypt certificate
#   command: /home/{{username.stdout}}/letsencrypt/certbot-auto install --apache --non-interactive --domain {{owncloud_url}} --cert-path /etc/letsencrypt/live/{{owncloud_url}}/cert.pem --key-path /etc/letsencrypt/live/{{owncloud_url}}/privkey.pem --fullchain-path /etc/letsencrypt/live/{{owncloud_url}}/fullchain.pem --chain-path /etc/letsencrypt/live/{{owncloud_url}}/chain.pem --redirect --hsts --domain {{owncloud_url}}
#   args: chdir=/home/{{username.stdout}}/letsencrypt
#   register: test2
#   become: yes
#   become_user: root
